# Generated by Django 3.2.4 on 2021-06-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cart_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='CartItems',
            new_name='cart_items',
        ),
    ]
